# Generated by Django 3.1.7 on 2021-03-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
